#!/usr/bin/env python

import sys
import shutil
from botox import Botox, BotoxException

try:
    elf_file = sys.argv[1]
except IndexError as e:
    sys.stderr.write("Usage: %s <input ELF file>\n" % sys.argv[0])
    sys.exit(1)

elf_cpy = elf_file + '.pre_botox'
shutil.copy(elf_file, elf_cpy)

try:
    new_entry_point = Botox(elf_file).patch()
    print "Patched file %s. New entry point is: 0x%.8X" % (elf_file, new_entry_point)
    sys.exit(0)
except BotoxException as e:
    sys.stderr.write(str(e) + "\n")
    sys.exit(2)
